---
- name: restart firewall
  service: 
    name: firewalld 
    state: restarted
- name: enable nginx
  service: 
    name: nginx 
    state: enabled
- name: restart nginx
  service:
    enabled: yes
    name: nginx 
    state: restarted 
